apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: load-balancer-webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer-webapp
  template:
    metadata:
      labels:
        app: load-balancer-webapp
    spec:
      containers:
      - name: webapp
        image: taorusb/spring-rest-example:v1
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: DB_URL
          value: "jdbc:mysql://mysql:3306/users_info"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        ports:
        - containerPort: 8080